import { oratorStd, graphik } from './ui/fonts';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${oratorStd.variable} ${graphik.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
